name: dslink_rpi
version: 0.2.1
description: Raspberry Pi DSLink
dependencies:
  dslink:
    git: https://github.com/IOT-DSA/sdk-dslink-dart.git
  rpi_gpio:
    git:
      url: https://github.com/kaendfinger/dart_rpi_gpio.git
      ref: caac0d1f70552e91d33614c6f84168bfe73c8a4d
